[ejs.landing]
updateAvailableTooltip = "Mise a jour disponible"
usernamePlaceholder = "Pseudo"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètre"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NOUVELLES"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Pas de serveur selectioner"
launchDetails = "Patienter.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "Regarde pour des nouvelles.."
newsErrorFailedSpan = "Erreur pendant le chargement des nouvelles"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Pas de nouvelles"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "Connexion Minecraft"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "E-MAIL OU NOM D'UTILISATEURTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de passe oublié?"
loginRememberMeText = "souviens-toi de moi?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à mojang ab."

[ejs.loginOptions]
loginOptionsTitle = "Options de connection"
loginWithMicrosoft = "Connection avec Microsoft"
loginWithMojang = "Connection avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponible"
serverSelectConfirm = "Selectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Selectionner un compte"
accountSelectConfirm = "Selectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètre"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "A propos"
navUpdates = "Mise a jour"
navDone = "Fermer"
tabAccountHeaderText = "Paramètre de compte"
tabAccountHeaderDesc = "Ajouter de nouveaux compte ou en modifier"
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte mojang (Pas recommender) "
minecraftTabHeaderText = "Paramètre de minecraft"
minecraftTabHeaderDesc = "Options par raport au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein ecrant."
autoConnectTitle = "Automatiquement connecter au serveur au lancement du jeu."
launchDetachedTitle = "Lancer le jeu détacher du procesus du launcher."
launchDetachedDesc = "Si le jeu n'est pas attacher, La fermeture du launcher va aussi fermer le jeu."
tabModsHeaderText = "Paramètre de Mod"
tabModsHeaderDesc = "Activer ou desactiver les Mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Options des Mods"
dropinMods = "Drop de Mods"
addMods = "Ajouter des Mods"
dropinRefreshNote = "(F5 Pour rafaichir)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activer ou désativer les shaders. S'il vous plaît Noter, les shaders ne fonctionneront correctement que sur des configurations puissantes. You may add custom packs here."
selectShaderpack = "Selectionner des shaderpacks"
tabJavaHeaderText = "Paramètre Java"
tabJavaHeaderDesc = "Manage the Java configuration (advanced)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximum"
minRAM = "RAM minimum"
memoryDesc = "La ram minimum recommander est de 3 gibyte. Définir les valeurs minimale et maximale sur la même valeur peut réduire le lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionnez un exécutable Java "
javaExecSelButtonText = "Choisir le fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin devrait se terminer avec <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir au JVM lors de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne devrait pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour de pré-libération."
allowPrereleaseDesc = "Les pré-sorties incluent de nouvelles fonctionnalités qui n'ont peut-être pas été entièrement testées ou intégrées.<br>Ce sera toujours vrai si vous utilisez une version pré-libération."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir le dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et les installations Java locaux seront stockés dans le répertoire de données.<br>Screenshots et les sauvegardes du monde sont stockées dans le dossier d'instance pour la configuration du serveur correspondant."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Afficher les informations et les notes de publication pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "version "
sourceGithub = "source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Notes de version"
changelog = "Changelog"
noReleaseNotes = "Pas de notes de libération"
viewReleaseNotes = "Afficher les notes de libération sur github"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et examiner les mises à jour pour le lanceur."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Mettre à jour les notes de version"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Connexion a Microsoft"
microsoftLogoutTitle = "Déconnexion de Microsoft"

[js.login]
login = "SE CONNECTER"
loggingIn = "SE CONNECTER"
success = "SUCCÈS"
tryAgain = "Essayer à nouveau"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue pendant la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "S'il vous plaît, attendez.."
failureTitle = "Erreur pendant le lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "D'accord"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "PLAYERS"

[js.landing.systemScan]
checking = "Vérification des informations du système.."
noCompatibleJava = "Pas de compatible<br>Installation Java trouvée"
installJavaMessage = "Afin de lancer Minecraft, Vous avez besoin d'une installation 64 bits de Java {major}. Souhaitez-vous que nous installions une copie?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparer le téléchargement de Java.."
javaDownloadFailureTitle = "Erreur pendant le téléchargement Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requise<br>lancer"
javaRequiredMessage = 'Une installation X64 valide de Java {major} est nécessaire pour lancer.<br><br>Veuillez vous référer à notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guide de gestion Java</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retourner"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver la distribution OpenJDK."
javaDownloadCorruptedError = "JDK téléchargé a un mauvais hachage, Le fichier peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé"

[js.landing.dlAsync]
loadingServerInfo = "Informations sur le serveur de chargement.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'indice de distribution.Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "S'il vous plaît, attendez.."
errorDuringLaunchTitle = "Erreur pendant le lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité du fichier.."
errorDuringFileVerificationTitle = "Erreur pendant la vérification du fichier"
downloadingFiles = "Télechargement des fichier.."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement de fichiers"
preparingToLaunch = "Se préparer à lancer.."
launchingGame = "Jeu de lancement.."
launchWrapperNotDownloaded = "Le fichier principalincipal, LaunchWrapper, Échec de l'échec correctement. Par conséquent, Le jeu ne peut pas être lancé.<br><br>Pour résoudre ce problème, Éteignez temporairement votre logiciel antivirus et lancez à nouveau le jeu.<br><br>Si vous avez le temps, s'il vous plaît <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">soumettre un problème</a> Et faites-nous savoir quel logiciel antivirus vous utilisez. Nous les contacterons et essaierons de redresser les choses."
doneEnjoyServer = "Fait. Profitez du serveur!"
checkConsoleForDetails = "Veuillez vérifier la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Vérifier les nouvelles"

[js.landing.discord]
loading = "Jeu en cours de chargement.."
joining = "Navigation à Westeros!"
joined = "Explorer le royaume!"

[js.overlay]
dismiss = "Rejeter"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "L'authentification Microsoft a échoué.Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "La déconnexion de Microsoft a échoué.Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Avertissement<br>C'est votre dernier compte"
lastAccountWarningMessage = "Afin d'utiliser le lanceur, vous devez être connecté à au moins un compte. Vous devrez vous connecter à nouveau après.<br><br>Êtes-vous sûr de vouloir vous déconnecter?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Échec de la suppression<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec de bascule<br>Un ou plus Drop-in Mods"
okButton = "D'accord"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Choisie: java {version} ({vendor})"
invalidSelection = "Selection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Impossible de charger les notes de libération."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouveau pré-version disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis github<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le lanceur et exécutez le DMG pour mettre à jour.</span>'
latestVersionTitle = "Vous exécutez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Connection a Microsoft a échoué"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale: Index de distribution incapable de charger"
fatalErrorMessage = "Une connexion n'a pas pu être établie sur nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour charger. <br><br>L'indice de distribution est un fichier essentiel qui fournit les dernières informations de serveur. Le launcher est incapable de commencer sans lui. Assurez-vous d'être connecté à Internet et de relancer l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous connecter à nouveaus connecter à nouveau."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous connecter à nouveau."
loginButton = "Se connecter"
selectAnotherAccountButton = "Sélectionnez un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur pendant la connexion:<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n'a pas encore de configuration de profil Minecraft. Si vous avez récemment acheté le jeu ou l'avez racheté via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n'avez pas encore acheté le jeu, Vous pouvez également faire ça sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur pendant la connexion:<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'a aucun compte Xbox qui lui est associé."
xblBannedTitle = "Erreur pendant la connexion:<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays où Xbox Live n'est pas disponible ou interdit."
under18Title = "Erreur pendant la connexion:<br>Approbation parentale requise"
under18Desc = "Les comptes pour les utilisateurs de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue pendant la connexion"
unknownDesc = "Une erreur inconnue s'est produite.Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne:<br>Méthode Non Autorisée"
methodNotAllowedDesc = "Méthode Non Autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne:<br>Pas trouvé"
notFoundDesc = "Le critère de terminaison de l'authentification n'a pas été trouvé.Veuillez signaler ce problème."
accountMigratedTitle = "Erreur pendant la connexion:<br>Le compte a migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Essayez à nouveau d'utiliser l'e-mail du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur pendant la connexion:<br>Les informations d'identification invalides"
invalidCredentialsDesc = "L'e-mail ou le mot de passe que vous avez saisi est incorrect.Veuillez réessayer."
tooManyAttemptsTitle = "Erreur pendant la connexion:<br>Trop d'essais"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion avec ce compte récemment. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur pendant la connexion:<br>jeton invalide"
invalidTokenDesc = "Le jeton d'accès fourni n'est pas valide."
tokenHasProfileTitle = "Erreur pendant la connexion:<br>Le jeton a un profil"
tokenHasProfileDesc = "Le jeton d'accès a déjà un profil attribué. La sélection des profils n'est pas encore implémentée."
credentialsMissingTitle = "erreurPendantLaConnexion:<br>Les informations d'identification manquantes"
credentialsMissingDesc = "Le nom d'utilisateur / le mot de passe n'a pas été soumis ou le mot de passe est inférieur à 3 caractères."
invalidSaltVersionTitle = "Erreur pendant la connexion:<br>Version de sel non valide"
invalidSaltVersionDesc = "Version de salt non valide."
unsupportedMediaTypeTitle = "Erreur interne:<br>Type de support non pris en charge"
unsupportedMediaTypeDesc = "Type de support non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur pendant la connexion:<br>Le compte a migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur pendant la connexion:<br>Inaccessible"
unreachableDesc = "Impossible d'atteindre les serveurs d'authentification. Assurez-vous qu'ils sont en ligne et que vous êtes connecté à Internet."
gameNotPurchasedTitle = "Erreur pendant la connexion:<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n'a pas acheté de copie de Minecraft. Vous pouvez acheter une copie surpie sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue pendant la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."
